server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://123.249.77.127:3307/yl_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ChenKo800
    driver-class-name: com.mysql.cj.jdbc.Driver
    # redis配置
  redis:
    host: 123.249.77.127
    port: 6379
    password: ChenKo800
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto


oss:
  accessKey: daddasd
  secretKey: weqeqwe
  bucket: sg-blog

# 上传模式 可选 oss或local  （http://和最后的/一定不能去！！！）
upload:
  mode: local
  local:
    # nginx映射本地文件路径，无域名则为 ip:83
    url: http://123.249.77.127:83/
    # 本地文件存储路径
    path: /usr/local/upload/